### ISSUE TITLE
Run all star across OSSF

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/.github#1]
Run https://github.com/ossf/allstar across OSSF

**Comment by naveensrinivasan** [comment]
Install https://github.com/apps/allstar-app at the org level. 

@jmertic would you be able to help with this?

**Comment by naveensrinivasan** [comment]
@jeffmendoza @justaugustus FYI...

**Comment by justaugustus** [comment]
Very awesome!

**Comment by jmertic** [comment]
Sorry for missing this! Installed now.
